### ISSUE TITLE
question regarding mouse support.  

### ISSUE THREAD

**Issue by mattmarcello** [urob/adv360-demo-config#4]
Thanks so much for this repo ( and your others ).  I just picked up an advantage pro and am new to zmk.  

I forked this repository and successfully flashed the device after making a few changes to this config.  Primarily, I just removed the Colemak layer.  

For whatever reason, the mouse support doesn't seem to work.  I can tell I am entering the layer because keys utilized by the layer and not falling through to lower layers, but still I am unable to move the cursor and simulate clicks.  Do you know if this is an OS dependent feature?  

Will continue to research on my own but figured I would ask in case I am missing something obvious.

**Comment by urob** [comment]
There's a mysterious bug that breaks mouse usage with the Adv360 over Bluetooth. It should be working when connected via usb. 

I plan to look into this a bit more once Kinesis has updated the driver to Zephyr 3.2.

**Comment by mattmarcello** [comment]
Ahh.  Interesting.  Thanks!
